services:
  - type: web
    name: codeforge-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: DB_CONNECT_STRING
        sync: false
      - key: JWT_KEY
        sync: false
      - key: GEMINI_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: REDDIS_HOST
        fromService:
          type: redis
          name: codeforge-redis
          property: host
      - key: REDDIS_PASS
        fromService:
          type: redis
          name: codeforge-redis
          property: password
      - key: FRONTEND_URL
        sync: false

  - type: redis
    name: codeforge-redis
    ipAllowList: [] # only allow internal connections
    plan: free
    maxmemoryPolicy: allkeys-lru
